# Generated by Django 4.2.1 on 2023-05-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.BigIntegerField(db_column='documento')),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('apellido', models.CharField(db_column='apellido', max_length=50)),
                ('telefono', models.BigIntegerField(db_column='telefono')),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
            ],
            options={
                'verbose_name': 'medico',
                'verbose_name_plural': 'medicos',
                'db_table': 'medico',
                'managed': True,
            },
        ),
    ]
