# Generated by Django 4.2.1 on 2023-05-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultorioModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.BigIntegerField(db_column='numero')),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
            ],
            options={
                'verbose_name': 'consultorio',
                'verbose_name_plural': 'consultorios',
                'db_table': 'consultorio',
                'managed': True,
            },
        ),
    ]
