# Generated by Django 4.2.1 on 2023-05-19 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultorio', '0001_initial'),
        ('paciente', '0001_initial'),
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.BigIntegerField(db_column='numero')),
                ('fecha', models.DateField(db_column='fecha')),
                ('hora', models.TimeField(db_column='hora')),
                ('estado_cita', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Atentido'), (3, 'Cancelada')], db_column='estado_cita', default=1)),
                ('observacion', models.CharField(db_column='observacion', max_length=200)),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('consultorio', models.ForeignKey(db_column='consultorio', on_delete=django.db.models.deletion.PROTECT, to='consultorio.consultoriomodel')),
                ('medico', models.ForeignKey(db_column='medico', on_delete=django.db.models.deletion.PROTECT, to='medico.medicomodel')),
                ('paciente', models.ForeignKey(db_column='paciente', on_delete=django.db.models.deletion.PROTECT, to='paciente.pacientemodel')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'db_table': 'cita',
                'managed': True,
            },
        ),
    ]
